name: Build and Release Ubuntu Image

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

env:
  PRODUCT_VERSION: "1.10.0"

jobs:
  build-packer-image:
    runs-on: ubuntu-latest
    name: Build and Release Ubuntu Image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Initialize Packer
        id: init
        run: |
          packer init .
        
      - name: Validate Packer template
        run: packer validate .

      - name: Build artifact
        run: packer build .

      - name: Rename artifact for release
        run: |
          mv output/ubuntu ubuntu-${{ github.ref_name }}.qcow2
          echo "ARTIFACT_NAME=ubuntu-${{ github.ref_name }}.qcow2" >> $GITHUB_ENV

      # - name: Upload to GitHub Release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     files: "${{ env.ARTIFACT_NAME }}"
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

