name: Build and Release Ubuntu Image

on:
  push:
    branches:
      - 'main' # Trigger on version tags like v1.0.0
  workflow_dispatch:

jobs:
  build-packer-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Packer
        uses: hashicorp/setup-packer@main
        with:
          version: 'latest'

      - name: Initialize Packer
        id: init
        run: |
          # The private key is stored as a secret in the GitHub repository
          echo "${{ secrets.PACKER_PRIVATE_KEY }}" > packer_key
          chmod 600 packer_key
          packer init .
        
      - name: Validate Packer template
        run: packer validate .

      - name: Build artifact
        run: packer build .

      - name: Rename artifact for release
        run: |
          mv output/ubuntu ubuntu-${{ github.ref_name }}.qcow2
          echo "ARTIFACT_NAME=ubuntu-${{ github.ref_name }}.qcow2" >> $GITHUB_ENV

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: "${{ env.ARTIFACT_NAME }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

