name: Build and Release Ubuntu Image

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

env:
  PRODUCT_VERSION: "1.14.1"

jobs:
  build-packer-image:
    runs-on: ubuntu-latest
    name: Build and Release Ubuntu Image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install QEMU
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-system-x86 qemu-utils cpu-checker

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Verify KVM availability
        run: |
          echo "--- Checking for /dev/kvm ---"
          ls -la /dev/kvm
          echo "--- Checking CPU virtualization support ---"
          egrep -c '(vmx|svm)' /proc/cpuinfo || echo "No virtualization flags found"
          echo "--- Running kvm-ok ---"
          sudo kvm-ok || echo "KVM check failed"

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Initialize Packer
        id: init
        run: packer init .
        
      - name: Validate Packer template
        run: packer validate .

      - name: Build artifact
        run: packer build .

      - name: Rename artifact for release
        run: |
          mv output/ubuntu ubuntu-${{ github.ref_name }}.qcow2
          echo "ARTIFACT_NAME=ubuntu-${{ github.ref_name }}.qcow2" >> $GITHUB_ENV
