name: Build and Release Ubuntu Image

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

env:
  PRODUCT_VERSION: "1.14.1"

jobs:
  build-packer-image:
    runs-on: ubuntu-latest
    name: Build and Release Ubuntu Image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Install QEMU and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-system-x86 qemu-utils genisoimage

      # Critical: Use the EXACT format from the working Actuated example
      - name: Create Cloud-Init ISO
        run: |
          # Create the ISO with exact parameters from Actuated
          genisoimage -output cidata.iso -input-charset utf-8 -volid cidata -joliet -r http/user-data http/meta-data
          
          # Verify
          ls -la cidata.iso
          file cidata.iso

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Initialize Packer
        id: init
        run: packer init .
        
      - name: Validate Packer template
        run: packer validate .

      - name: Build artifact
        run: packer build .

      - name: Rename artifact for release
        run: |
          mv artifacts/*.img ubuntu-${{ github.ref_name }}.img
          echo "ARTIFACT_NAME=ubuntu-${{ github.ref_name }}.img" >> $GITHUB_ENV
